language: android
android:
  components:
    - platform-tools
    - tools
    - android-22
install: npm install
script:
  - node_modules/cordova/bin/cordova platform add android
  - node_modules/cordova/bin/cordova build
